### ISSUE TITLE
get_token not working

### ISSUE THREAD

**Issue by rastislavpapp** [Yuuyuuei/Torapi#3]
Hello, I'm trying to get a token, according to the api docs v2 it is supposed to be a get request for https://torrentapi.org/pubapi_v2.php?get_token=get_token, if I'm not mistaken. Unfortunately, this does not work (and I had it working previously, although it was a long time ago). It says Invalid API parameters.

**Comment by Yuuyuuei** [comment]
Hey just found out that you need to also give it an app_id so https://torrentapi.org/pubapi_v2.php?app_id=Torapi&get_token=get_token

However now I'm have encountered an issue with encoding the JSON that I get from requests

**Comment by rastislavpapp** [comment]
Great, thank you!
